---
language: ruby
sudo: false
cache: bundler
bundler_args: --without system_tests
script: "bundle exec rake test"
matrix:
  fast_finish: true
  include:
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.1.10
    sudo: required
    services: docker
    bundler_args:
    script: bundle exec rake beaker
