---
language: ruby
sudo: false
cache: bundler
script: "bundle exec rake test"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.10
    env: PUPPET_GEM_VERSION="~> 4.5"
  - rvm: 2.1.10
    env: PUPPET_GEM_VERSION="~> 4.5" FUTURE_PARSER="yes"
  - rvm: 2.2.0
    env: PUPPET_GEM_VERSION="~> 4.5"
  - rvm: 2.2.10
    env: PUPPET_GEM_VERSION="~> 4.5"
    sudo: required
    services: docker
    bundler_args:
    script: bundle exec rake beaker:ubuntu-14.04-docker
  - rvm: 2.2.10
    env: PUPPET_GEM_VERSION="~> 4.5"
    sudo: required
    services: docker
    bundler_args:
    script: bundle exec rake beaker:ubuntu-16.04-docker
  - rvm: 2.4.9
    # Puppetlabs don't package Puppet 4 for >= Bionic
    env: BEAKER_PUPPET_COLLECTION="puppet5"
    sudo: required
    services: docker
    bundler_args:
    script: bundle exec rake beaker:ubuntu-18.04-docker
